main/urls.py
from django.conf.urls import url
from .views import *

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$', login, name='login'),
    url(r'^home/', index, name='index'),
    url(r'^user/', user, name='user'),
    url(r'^signup/', signup, name='signup'),
    url(r'^auth_check/', auth_check, name='check'),
    url(r'^logout/', logout, name='logout'),
    url(r'^invalid/', invalid, name='invalid'),
    url(r'^customer/$', customer, name='customer'),
    url(r'^customer_list/', customer_list, name='customer_list'),
    url(r'^reports/', reports, name="reports"),
    url(r'^dashboard/', dashboard, name="dashboard"),
    url(r'^location_tracking/', location_tracking, name="location_tracking"),
    url(r'^company_profile/$', company_profile, name="company_profile"),
    url(r'^company_profile/add/', company_profile_add, name="company_profile_add"),
    #id,slug based url below this
    url(r'^(?P<slug>[\w-]+)/$', user_details, name='user_details'),
    url(r'^(?P<slug>[\w-]+)/edit/', edit_user, name='edit_user'),
    url(r'^(?P<slug>[\w-]+)/delete/', delete_user, name='delete_user'),
    url(r'^customer/(?P<slug1>[\w-]+)/$', customer_details, name='customer_details'),
    url(r'^customer/(?P<slug1>[\w-]+)/edit/', edit_customer, name='edit_customer'),
    url(r'^customer/(?P<slug1>[\w-]+)/delete/', delete_customer, name='delete_customer'),
    url(r'^company_profile_edit/(\d+)/', company_profile_edit, name="company_profile_edit"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

msg/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    # url(r'^$', msg, name='msg'),
    url(r'^msg_list/$', msg, name='msg'),
    url(r'^add_msg/$', msg_add, name="msg_add"),
    # id,slug based url below this'
    url(r'^msg_list/(\d+)/', msg_user_add, name="msg_user_add"),
    # url(r'^add_msg/(\d+)/', msg_user_add, name="msg_user_add"),
    url(r'^(?P<slug>[\w-]+)/$', msg_details, name='msg_details'),
    url(r'^(?P<slug>[\w-]+)/edit/', msg_edit, name='msg_edit'),
    url(r'^(?P<slug>[\w-]+)/delete/', msg_delete, name='msg_delete'),
]

sample_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('main.urls', 'main'), namespace="main")),
    url(r'^product/', include(('product.urls', 'product'), namespace="product")),
    url(r'^order/', include(('order.urls', 'order'), namespace="order")),
]

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelChoiceField
from .models import *
from .models1 import *


USER_TYPE = (
    ('salesmanager','SALES-MANAGER'),
    ('salesmen','SALESMEN'),
)

STATUS = (
    ('active','ACTIVE'),
    ('inactive','INACTIVE'),
)

# s_admin = Profile.objects.filter(user_type='salesadmin')
s_manager = Profile.objects.filter(user_type='salesmanager')

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(required=True, widget=forms.TextInput())
    last_name = forms.CharField(required=True, widget=forms.TextInput())
    address = forms.CharField(required=True, widget=forms.TextInput())
    state = forms.CharField(required=True, widget=forms.TextInput())
    city = forms.CharField(required=True, widget=forms.TextInput())
    country = forms.CharField(required=True, widget=forms.TextInput())
    pincode = forms.IntegerField(required=True,widget=forms.NumberInput())
    user_type = forms.ChoiceField(choices=USER_TYPE, required=True, widget=forms.Select(attrs={'class':'dropdown-item', 'style':'width:200px'}))
    # sale_admin = ModelChoiceField(queryset=s_admin, required=False)
    sale_manager = ModelChoiceField(queryset=s_manager, required=False)
    status = forms.ChoiceField(choices=STATUS, required=True, widget=forms.Select(attrs={'class':'dropdown-item', 'style':'width:200px'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput())
    profile_pic = forms.FileField(required=False)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'profile_pic',
            'username',
            'status',
            'email',
            'address',
            'state',
            'pincode',
            'city',
            'country',
            'user_type',
            # 'sale_admin',
            'sale_manager',
            'password1',
            'password2',
        )


class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(required=True, widget=forms.TextInput())
    last_name = forms.CharField(required=True, widget=forms.TextInput())
    address = forms.CharField(required=True, widget=forms.TextInput())
    state = forms.CharField(required=True, widget=forms.TextInput())
    city = forms.CharField(required=True, widget=forms.TextInput())
    country = forms.CharField(required=True, widget=forms.TextInput())
    pincode = forms.IntegerField(required=True,widget=forms.NumberInput())
    user_type = forms.ChoiceField(choices=USER_TYPE, required=True, widget=forms.Select(attrs={'class':'dropdown-item', 'style':'width:200px'}))
    # sale_admin = ModelChoiceField(queryset=s_admin, required=False)
    sale_manager = ModelChoiceField(queryset=s_manager, required=False)
    status = forms.ChoiceField(choices=STATUS, required=True, widget=forms.Select(attrs={'class':'dropdown-item', 'style':'width:200px'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput())
    profile_pic = forms.FileField()

    class Meta:
        model = Profile
        fields = (
            'first_name',
            'last_name',
            'profile_pic',
            'status',
            'email',
            'address',
            'state',
            'pincode',
            'city',
            'country',
            'user_type',
            # 'sale_admin',
            'sale_manager',
        )


class CustomerForm(forms.ModelForm):
    sale_manager = ModelChoiceField(queryset=s_manager, required=True)

    class Meta:
        model = Customer
        fields = (
            'name',
            'customer_code',
            'sale_manager',
            'status',
            'address',
            'pincode',
            'country',
            'city',
            'state',
            'area',
            'status',
            'lattitude',
            'longitude',
            'email',
            'mobile',
        )


class CompanyProfileEditForm(forms.ModelForm):

    class Meta:
        model = Company_Profile
        exclude = {

        }

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import auth
from .forms import *
from .models import *
from .models1 import *


def index(request):
    return render(request, 'main/index.html')


def user(request):
    if request.user.is_authenticated:
        # admin = Profile.objects.filter(user_type='salesadmin')
        manager = Profile.objects.filter(user_type='salesmanager')
        men = Profile.objects.filter(user_type='salesmen')
        context = {
            # 'admin': admin,
            'manager': manager,
            'men': men,
            'active10': 'active',
            'dropdown5': 'dropdown-container1',
        }
        return render(request, 'main/user.html', context)
    else:
        return render(request, 'main/user.html')


def user_details(request, slug):
    instance = get_object_or_404(Profile, slug=slug)
    context = {
        'instance': instance,
        'active10': 'active',
        'dropdown5': 'dropdown-container1',
    }
    return render(request, 'main/user_details.html', context)


def signup(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = SignUpForm(request.POST, request.FILES)
            if form.is_valid():
                f = form.save()
                f.refresh_from_db()  # load the profile instance created by the signal
                f.profile.user_type = form.cleaned_data.get('user_type')
                f.profile.sale_admin = str(form.cleaned_data.get('sale_admin'))
                f.profile.sale_manager = str(form.cleaned_data.get('sale_manager'))
                f.profile.first_name = form.cleaned_data.get('first_name')
                f.profile.last_name = form.cleaned_data.get('last_name')
                f.profile.email = form.cleaned_data.get('email')
                f.profile.pincode = form.cleaned_data.get('pincode')
                f.profile.state = form.cleaned_data.get('state')
                f.profile.city = form.cleaned_data.get('city')
                f.profile.country = form.cleaned_data.get('country')
                f.profile.status = form.cleaned_data.get('status')
                f.profile.address = form.cleaned_data.get('address')
                f.profile.profile_pic = form.cleaned_data.get('profile_pic')
                f.save()
                # return redirect('main:user')
                return HttpResponseRedirect(f.profile.get_absolute_url())
        else:
            form = SignUpForm()
        context = {
            'form': form,
            'active10': 'active',
            'dropdown5': 'dropdown-container1',
        }
        return render(request, 'main/signup.html', context)
    else:
        return render(request, 'main/not_authorised.html')


def edit_user(request, slug):
    instance = get_object_or_404(Profile, slug=slug)
    if request.user.is_superuser:
        if request.method == 'POST':
            form = EditUserForm(request.POST, request.FILES, instance=instance)
            if form.is_valid():
                f = form.save()
                f.refresh_from_db()  # load the profile instance created by the signal
                f.user_type = form.cleaned_data.get('user_type')
                f.sale_admin = str(form.cleaned_data.get('sale_admin'))
                f.sale_manager = str(form.cleaned_data.get('sale_manager'))
                f.first_name = form.cleaned_data.get('first_name')
                f.last_name = form.cleaned_data.get('last_name')
                f.email = form.cleaned_data.get('email')
                f.pincode = form.cleaned_data.get('pincode')
                f.state = form.cleaned_data.get('state')
                f.city = form.cleaned_data.get('city')
                f.country = form.cleaned_data.get('country')
                f.status = form.cleaned_data.get('status')
                f.address = form.cleaned_data.get('address')
                f.profile_pic = form.cleaned_data.get('profile_pic')
                f.save()
                # return redirect('main:user')
                return HttpResponseRedirect(f.get_absolute_url())
        else:
            form = EditUserForm(instance=instance)
        context = {
            'form': form,
            'active10': 'active',
            'dropdown5': 'dropdown-container1',
        }
        return render(request, 'main/signup.html', context)
    else:
        return render(request, 'main/not_authorised.html')


def delete_user(request, slug):
    instance = get_object_or_404(Profile, slug=slug)
    instance_user = User.objects.get(username=instance.user.username)
    instance.delete()
    # print(instance_user)
    instance_user.delete()
    return redirect('main:user')


def login(request):
    if request.user.is_authenticated:
        return render(request, 'main/index.html')
    else:
        return render(request, 'login.html')


def auth_check(request):
    username = request.POST['username']
    password = request.POST['password']
    user = auth.authenticate(username=username,password=password)

    if user is not None:
        auth.login(request,user)
        return redirect('main:index')
    else:
        return redirect('main:invalid')


def invalid(request):
    return render(request, 'main/invalid.html')


def logout(request):
    auth.logout(request)
    return redirect('main:login')


def customer(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = CustomerForm(request.POST)
            if form.is_valid():
                f = form.save(commit=False)
                f.sale_manager = str(form.cleaned_data.get('sale_manager'))
                f.save()
                # return redirect('main:customer_list')
                return HttpResponseRedirect(f.get_absolute_url1())
        else:
            form = CustomerForm()
        context = {
            'form': form,
            'active5': 'active',
            'dropdown2': 'dropdown-container1',
        }
        return render(request, 'main/customer.html', context)
    else:
        return render(request, 'main/not_authorised.html')


def customer_list(request):
    sale_manager = Profile.objects.filter(user_type='salesmanager')
    customer = Customer.objects.all()
    context = {
        'sale_manager': sale_manager,
        'customer': customer,
        'active5': 'active',
        'dropdown2': 'dropdown-container1',
    }
    return render(request, 'main/customer_list.html', context)


def customer_details(request, slug1):
    instance = get_object_or_404(Customer, slug1=slug1)
    context = {
        'instance': instance,
        'active5': 'active',
        'dropdown2': 'dropdown-container1',
    }
    return render(request, 'main/customer_details.html', context)


def edit_customer(request, slug1):
    instance = get_object_or_404(Customer, slug1=slug1)
    if request.user.is_superuser:
        if request.method == 'POST':
            form = CustomerForm(request.POST,instance=instance)
            if form.is_valid():
                f = form.save(commit=False)
                f.sale_manager = str(form.cleaned_data.get('sale_manager'))
                f.save()
                # return redirect('main:customer_list')
                return HttpResponseRedirect(f.get_absolute_url1())
        else:
            form = CustomerForm(instance=instance)
        context = {
            'form': form,
            'active5': 'active',
            'dropdown2': 'dropdown-container1',
        }
        return render(request, 'main/customer.html', context)
    else:
        return render(request, 'main/not_authorised.html')


def delete_customer(request, slug1):
    instance = get_object_or_404(Customer, slug1=slug1)
    instance.delete()
    return redirect('main:customer_list')


def reports(request):
    context = {
        'active9': 'active',
    }
    return render(request, 'main/reports.html', context)


def dashboard(request):
    context = {
        'active1': 'active',
    }
    return render(request, 'main/dashboard.html', context)


def location_tracking(request):
    context = {
        'active8': 'active',
    }
    return render(request, 'main/location_tracking.html', context)


def company_profile(request):
    cp = Company_Profile.objects.all()
    context = {
        'cp': cp,
        'active11': 'active',
    }
    if cp.count() == 0:
        if request.user.is_superuser:
            return redirect('main:company_profile_add')
        else:
            return render(request, 'main/no_data_found.html')
    else:
        return render(request, 'main/company_profile.html', context)


def company_profile_add(requset):
    if requset.method == 'POST':
        form = CompanyProfileEditForm(requset.POST)
        if form.is_valid():
            form.save()
            return redirect('main:company_profile')
    else:
        form = CompanyProfileEditForm()
    context = {
        'form': form,
        'active11': 'active',
    }
    if requset.user.is_superuser:
        return render(requset, 'main/company_profile_add.html', context)
    else:
        return render(requset, 'main/not_authorised.html')


def company_profile_edit(requset, id):
    instance = Company_Profile.objects.get(id=id)
    if requset.method == 'POST':
        form = CompanyProfileEditForm(requset.POST,instance=instance)
        if form.is_valid():
            form.save()
            return redirect('main:company_profile')
    else:
        form = CompanyProfileEditForm(instance=instance)
    context = {
        'form': form,
        'instance': instance,
        'active11': 'active',
    }
    if requset.user.is_superuser:
        return render(requset, 'main/company_profile_add.html', context)
    else:
        return render(requset, 'main/not_authorised.html')

templates/main/company_profile.html
{% extends 'base.html' %}

{% block content %}

    {% for cp in cp %}

        <div class="panel panel-default">
            <div class="container">
                <div class="col-sm-6">
                    <big><b>Profile</b></big>
                </div>
                <div class="col-sm-6" align="right">
                    <a href="{% url 'main:company_profile_edit' cp.id %}" class="btn btn-primary btn-sm">
                        Edit
                    </a>
                </div>
            </div>
        </div>


        <h3><b>Profile Info</b></h3>
        <hr/>
        <div class="container" style="margin:0px;">
            <div class="col-sm-3">
                {% if cp.pic %}
                    <img src="{{cp.pic.url}}" width="130px" height="130px" />
                {% else %}
                    <img src="https://i.stack.imgur.com/34AD2.jpg" width="130px" height="130px" />
                {% endif %}
            </div>
            <div class="col-sm-3">
                <b>Name</b> <br/>
                {{cp.name}}
                <br/><br/><br/><br/>
                <b>Phone</b> <br/>
                {{cp.phone}}
                <br/>
            </div>
            <div class="col-sm-3">
                <b>Website</b> <br/>
                {{cp.website}}
                <br/><br/><br/><br/>
                <b>Fax</b> <br/>
                {{cp.fax}}
                <br/>
            </div>
            <div class="col-sm-3">
                <b>Email</b> <br/>
                {{cp.email}}
            </div>
        </div>
        <br/>

        <h3><b>Contact Person</b></h3>
        <hr/>
        <div class="container" style="margin:0px;">
            <div class="col-sm-4">
                <b>Contact Person Name</b> <br/>
                {{ request.user.profile.first_name }} {{ request.user.profile.last_name }}
            </div>
            <div class="col-sm-4">
                <b>Contact Person Contact Number</b> <br/>
                {{ request.user.profile.mobile }}
            </div>
            <div class="col-sm-4">

            </div>
        </div>
        <br/>

        <h3><b>Address Details</b></h3>
        <hr/>
        <div class="container" style="margin:0px;">
            <div class="col-sm-3">
                <b>Address</b> <br/>
                {{cp.address}}
                <br/><br/><br/><br/>
                <b>City</b> <br/>
                {{cp.city}}
            </div>
            <div class="col-sm-3">
                <b>Pincode</b> <br/>
                {{cp.pincode}}
            </div>
            <div class="col-sm-3">
                <b>Country</b> <br/>
                {{cp.country}}
            </div>
            <div class="col-sm-3">
                <b>State</b> <br/>
                {{cp.state}}
            </div>
        </div>
        <br/>

        <h3><b>Account Details</b></h3>
        <hr/>
        <div class="container" style="margin:0px;">
            <div class="col-sm-3">
                <b>PAN</b> <br/>
                {{cp.pan}}
            </div>
            <div class="col-sm-3">
                <b>GST</b> <br/>
                {{cp.gst}}
            </div>
            <div class="col-sm-3">
                <b>TAN</b> <br/>
                {{cp.tan}}
            </div>
            <div class="col-sm-3">

            </div>
        </div>
        <br/>

    {% endfor %}

{% endblock %}

templates/main/customer_list.html
{% extends 'base.html' %}

{% block content %}



<div class="container" style="margin:0px;padding:0px 0px 0px 0px;">
    <div class="col-sm-6" style="color:grey;font-family:">
        <h2>
            <b>CUSTOMER</b>
        </h2>
    </div>
    {% if request.user.is_superuser %}
        <div class="col-sm-6" align="right" style="margin-top:15px;">
            <a href="{% url 'main:customer' %}" class="btn btn-info">
                <i class="glyphicon glyphicon-plus"></i> Create New
            </a>
        </div>
    {% endif %}
</div>
<hr/>

<h3>
    <span style="color:#1dadc6;font-family:serif">Top News</span>
</h3>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead style="background-color:black;color:white">
        <tr>
            <th>
                NAME
            </th>
            <th>
                CUSTOMER CODE
            </th>
            <th>
                SALES-MANAGER
            </th>
            <th>
                E-MAIL
            </th>
            <th>
                CONTACT
            </th>
            <th>
                STATUS
            </th>
            <th>
                ADDRESS
            </th>
            <th>
                CITY
            </th>
            <th>
                STATE
            </th>
            <th>
                COUNTRY
            </th>
            <th>
                PINCODE
            </th>
            <th>
                VIEW
            </th>
            <th>
                EDIT
            </th>
            <th>
                DELETE
            </th>
        </tr>
    </thead>
    {% for cust in customer %}
        <tr>
            <td>
                {{cust.name}}
            </td>
            <td>
                {{cust.customer_code}}
            </td>
            <td>
                {{cust.sale_manager}}
            </td>
            <td>
                {{cust.email}}
            </td>
            <td>
                {{cust.mobile}}
            </td>
            <td>
                {% if cust.status %}
                    Active
                {% else %}
                    In-Active
                {% endif %}
            </td>
            <td>
                {{cust.address}}
            </td>
            <td>
                {{cust.city}}
            </td>
            <td>
                {{cust.state}}
            </td>
            <td>
                {{cust.country}}
            </td>
            <td>
                {{cust.pincode}}
            </td>
            <td>
                <a href="{{cust.get_absolute_url1}}" class="btn btn-default btn-sm" style="align:right;">
                    view
                </a>
            </td>
            <td>
                <a href="{{cust.get_absolute_url1}}edit" class="btn btn-info btn-sm" style="align:right;">
                    <i class="glyphicon glyphicon-pencil"></i>
                </a>
            </td>
            <td>
                <a href="{{cust.get_absolute_url1}}delete" class="btn btn-danger btn-sm" style="align:right;">
                    <i class="glyphicon glyphicon-trash"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
</table>
<br/>


    <!--{% for sm in sale_manager %}-->
        <!--<ul>-->
            <!--<li>-->
            <!--<a href="{{sm.get_absolute_url}}">-->
                <!--{{ sm }}-->
            <!--</a>-->
            <!--{% for cust in customer %}-->
                <!--<ul>-->
                    <!--{% if cust.sale_manager == sm.user.username %}-->
                        <!--<li>-->
                            <!--<a href="{{cust.get_absolute_url1}}">-->
                                <!--{{cust}} <span style="color:grey"></span>-->
                            <!--</a>-->
                        <!--</li>-->
                    <!--{% endif %}-->
                <!--</ul>-->
            <!--{% endfor %}-->
            <!--</li>-->
        <!--</ul>-->
    <!--{% endfor %}-->

{% endblock %}

templates/main/index.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

templates/main/location_tracking.html
{% extends 'base.html' %}
{% block content %}


{% endblock %}

templates/main/user.html
{% extends 'base.html' %}

{% block content %}
    <!--{{ request.user }}<br/>-->
    <!--{{ admin }}<br/>-->
    <!--{{ manager }}<br/>-->
    <!--{{ men }}<br/>-->

    <!--<br/>-->
    <!--{% if request.user.is_superuser %}-->
        <!--<a href="{{request.user.profile.get_absolute_url}}">-->
            <!--{{ request.user.profile.first_name}} {{ request.user.profile.last_name}}-->
        <!--</a>-->
        <!--<ul>-->
            <!--{% for j in manager %}-->
                <!--<li>-->
                    <!--<a href="{{j.get_absolute_url}}">-->
                        <!--{{j.first_name}} {{j.last_name}}-->
                    <!--</a>-->
                    <!--<ul>-->
                        <!--{% for k in men %}-->
                            <!--{% if k.sale_manager == j.user.username %}-->
                                <!--<li>-->
                                    <!--<a href="{{k.get_absolute_url}}">-->
                                        <!--{{k.first_name}} {{k.last_name}}-->
                                    <!--</a>-->
                                <!--</li>-->
                            <!--{% endif %}-->
                        <!--{% endfor %}-->
                    <!--</ul>-->
                <!--</li>-->
            <!--{% endfor %}-->
        <!--</ul>-->
    <!--{% elif request.user.profile.user_type == 'salesmanager' %}-->
        <!--<a href="{{request.user.profile.get_absolute_url}}">-->
            <!--{{ request.user.profile.first_name}} {{ request.user.profile.last_name }}<br/>-->
        <!--</a>-->
        <!--<ul>-->
            <!--{% for j in manager %}-->
                <!--{% if j.user.username == request.user.username %}-->
                    <!--{% for k in men %}-->
                        <!--{% if k.sale_manager == j.user.username %}-->
                            <!--<li>-->
                                <!--<a href="{{k.get_absolute_url}}">-->
                                    <!--{{k.first_name}} {{k.last_name}}-->
                                <!--</a>-->
                            <!--</li>-->
                        <!--{% endif %}-->
                    <!--{% endfor %}-->
                <!--{% endif %}-->
            <!--{% endfor %}-->
        <!--</ul>-->
    <!--{% else %}-->
        <!--<a href="{{request.user.profile.get_absolute_url}}">-->
            <!--{{ request.user.profile.first_name}} {{ request.user.profile.last_name }}<br/>-->
        <!--</a>-->
    <!--{% endif %}-->

    <div class="container" style="margin:0px;padding:0px 0px 0px 0px;">
        <div class="col-sm-6" style="color:grey;font-family:">
            <h2>
                <b>ALL USER</b>
            </h2>
        </div>
        {% if request.user.is_superuser %}
            <div class="col-sm-6" align="right" style="margin-top:15px;">
                <a href="{% url 'main:signup' %}" class="btn btn-info">
                    <i class="glyphicon glyphicon-plus"></i> Create New
                </a>
            </div>
        {% endif %}
    </div>
<hr/>

<h3>
    <span style="color:#1dadc6;font-family:serif">SALES-MANAGER</span>
</h3>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead style="background-color:black;color:white">
        <tr>
            <th>
                NAME
            </th>
            <th>
                E-MAIL
            </th>
            <th>
                STATUS
            </th>
            <th>
                USER ROLE
            </th>
            <th>
                ADDRESS
            </th>
            <th>
                CITY
            </th>
            <th>
                STATE
            </th>
            <th>
                COUNTRY
            </th>
            <th>
                PINCODE
            </th>
            <th>

            </th>
        </tr>
    </thead>
    {% for j in manager %}
        <tr>
            <td>
                {{j.first_name}} {{j.last_name}}
            </td>
            <td>
                {{j.email}}
            </td>
            <td>
                {{j.status}}
            </td>
            <td>
                {{j.user_type}}
            </td>
            <td>
                {{j.address}}
            </td>
            <td>
                {{j.city}}
            </td>
            <td>
                {{j.state}}
            </td>
            <td>
                {{j.country}}
            </td>
            <td>
                {{j.pincode}}
            </td>
            <td>
                <a href="{{j.get_absolute_url}}" class="btn btn-default btn-sm">
                    view
                </a>
                <a href="{{j.get_absolute_url}}edit" class="btn btn-info btn-sm">
                    <i class="glyphicon glyphicon-pencil"></i>
                </a>                 &nbsp; &nbsp;
                <a href="{{j.get_absolute_url}}delete" class="btn btn-danger btn-sm">
                    <i class="glyphicon glyphicon-trash"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
</table>
<br/>

<h3 style="font-size:#1dadc6;">
    <span style="color:#1dadc6;font-family:serif">SALESMEN</span>
</h3>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead style="background-color:black;color:white">
        <tr>
            <th>
                NAME
            </th>
            <th>
                E-MAIL
            </th>
            <th>
                STATUS
            </th>
            <th>
                USER ROLE
            </th>
            <th>
                SALES-MANAGER
            </th>
                        <th>
                ADDRESS
            </th>
            <th>
                CITY
            </th>
            <th>
                STATE
            </th>
            <th>
                COUNTRY
            </th>
            <th>
                PINCODE
            </th>
            <th>

            </th>
        </tr>
    </thead>
    {% for j in manager %}
        {% for k in men %}
            {% if k.sale_manager == j.user.username %}
                <tr>
                    <td>
                        {{k.first_name}} {{k.last_name}}
                    </td>
                    <td>
                        {{k.email}}
                    </td>
                    <td>
                        {{k.status}}
                    </td>
                    <td>
                        {{k.user_type}}
                    </td>
                    <td>
                        {{k.sale_manager}}
                    </td>
                    <td>
                        {{k.address}}
                    </td>
                    <td>
                        {{k.city}}
                    </td>
                    <td>
                        {{k.state}}
                    </td>
                    <td>
                        {{k.country}}
                    </td>
                    <td>
                        {{k.pincode}}
                    </td>
                    <td>
                        <a href="{{k.get_absolute_url}}" class="btn btn-default btn-sm">
                            view
                        </a>
                        <a href="{{k.get_absolute_url}}edit" class="btn btn-info btn-sm">
                            <i class="glyphicon glyphicon-pencil"></i>
                        </a>
                        <a href="{{k.get_absolute_url}}delete" class="btn btn-danger btn-sm">
                            <i class="glyphicon glyphicon-trash"></i>
                        </a>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
    {% endfor %}
</table>


{% endblock %}