msg/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    # url(r'^$', msg, name='msg'),
    url(r'^msg_list/$', msg, name='msg'),
    url(r'^add_msg/$', msg_add, name="msg_add"),
    # id,slug based url below this'
    url(r'^msg_list/(\d+)/', msg_user_add, name="msg_user_add"),
    # url(r'^add_msg/(\d+)/', msg_user_add, name="msg_user_add"),
    url(r'^(?P<slug>[\w-]+)/$', msg_details, name='msg_details'),
    url(r'^(?P<slug>[\w-]+)/edit/', msg_edit, name='msg_edit'),
    url(r'^(?P<slug>[\w-]+)/delete/', msg_delete, name='msg_delete'),
]

product/urls.py
from django.conf.urls import url
from .views import *

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^category/$', category, name="category"),
    url(r'^add_category/', add_category, name="add_category"),

    url(r'^product/', product, name="product"),
    url(r'^add_product/', add_product, name="add_product"),

    url(r'^price_category/$', price_category, name="price_category"),
    url(r'^add_price_category/', add_price_category, name="add_price_category"),


    url(r'^(?P<slug>[\w-]+)/$', product_detail, name="product_details"),
    url(r'^(?P<slug>[\w-]+)/edit/', product_edit, name="product_edit"),
    url(r'^(?P<slug>[\w-]+)/delete/', product_delete, name="product_delete"),

    url(r'^category/(?P<slug1>[\w-]+)/$', category_detail, name="category_details"),
    url(r'^category/(?P<slug1>[\w-]+)/edit/', category_edit, name="category_edit"),
    # url(r'^category/(?P<slug1>[\w-]+)/delete/', category_delete, name="category_delete"),

    url(r'^price_category/(?P<slug2>[\w-]+)/$', price_category_detail, name="price_category_details"),
    url(r'^price_category/(?P<slug2>[\w-]+)/edit/', price_category_edit, name="price_category_edit"),
    url(r'^price_category/(?P<slug2>[\w-]+)/delete/', price_category_delete, name="price_category_delete"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sample_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('main.urls', 'main'), namespace="main")),
    url(r'^product/', include(('product.urls', 'product'), namespace="product")),
    url(r'^order/', include(('order.urls', 'order'), namespace="order")),
]

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from .models1 import *


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    product_code = models.CharField(max_length=100, blank=True, null=True)
    discount = models.PositiveIntegerField(blank=True, null=True)
    tax = models.PositiveIntegerField(blank=True, null=True)
    image = models.FileField(upload_to='product', null=True, blank=True)
    price = models.PositiveIntegerField()
    status = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now=True, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("product:product_details", kwargs={"slug" : self.slug})

    class Meta:
        ordering = ["-timestamp" , "-last_updated"]

def create_slug(instance, new_slug=None):
    slug = slugify(instance.name)

    if new_slug is not None:
        slug = new_slug
    qs = Product.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()

    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_product_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
pre_save.connect(pre_save_product_receiver, sender=Product)

product/forms.py
from django import forms
from .models import *
from .models1 import *
from .models2 import *


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            'category',
        ]


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'category',
            'name',
            'description',
            'product_code',
            'price',
            'discount',
            'tax',
            'image',
            'status',
        ]


class PriceCategoryForm(forms.ModelForm):
    class Meta:
        model = PriceCategory
        fields = [
            'price',
        ]

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from .forms import *
from .models import *
from .models1 import *
from .models2 import *


def category(request):
    category = Category.objects.all()
    context = {
        'category': category,
        'active4': 'active',
        'dropdown1': 'dropdown-conatiner1',
    }
    return render(request, 'product/category.html', context)


def product(request):
    product = Product.objects.all()
    context = {
        'product': product,
        'active4': 'active',
        'dropdown1': 'dropdown-conatiner1',
    }
    return render(request, 'product/product.html', context)


def price_category(request):
    price = PriceCategory.objects.all()
    context = {
        'price': price,
        'active4': 'active',
        'dropdown1': 'dropdown-conatiner1',
    }
    return render(request, 'product/price_category.html', context)


def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.created_by = request.user
            f.save()
            return redirect(f.get_absolute_url1())
    else:
        form = CategoryForm()
    context = {
        'form': form,
        'active4': 'active',
        'dropdown1': 'dropdown-conatiner1',
    }
    if request.user.is_superuser:
        return render(request, 'product/add_category.html', context)
    else:
        return render(request, 'main/not_authorised.html')


def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.created_by = request.user
            f.save()
            # return redirect('product:index')
            return HttpResponseRedirect(f.get_absolute_url())
    else:
        form = ProductForm()
    context = {
        'form': form,
        'active4': 'active',
        'dropdown1': 'dropdown-conatiner1',
    }
    if request.user.is_superuser:
        return render(request, 'product/add_product.html', context)
    else:
        return render(request, 'main/not_authorised.html')


def add_price_category(request):
    if request.method == 'POST':
        form = PriceCategoryForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.created_by = request.user
            f.save()
            # return redirect('product:index')
            return HttpResponseRedirect(f.get_absolute_url2())
    else:
        form = PriceCategoryForm()
    context = {
        'form': form,
        'active4': 'active',
        'dropdown1': 'dropdown-conatiner1',
    }
    if request.user.is_superuser:
        return render(request, 'product/add_price_category.html', context)
    else:
        return render(request, 'main/not_authorised.html')


def category_detail(request, slug1):
    instance = get_object_or_404(Category, slug1=slug1)
    product =  Product.objects.all()
    context = {
        'instance': instance,
        'product': product,
        'active4': 'active',
        'dropdown1': 'dropdown-conatiner1',
    }
    return render(request, 'product/category_details.html', context)


def category_edit(request, slug1):
    instance = get_object_or_404(Category, slug1=slug1)
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            f = form.save(commit=False)
            f.created_by = request.user
            f.save()
            # return redirect('product:index')
            return HttpResponseRedirect(f.get_absolute_url1())
    else:
        form = CategoryForm(instance=instance)
    context = {
        'form': form,
        'active4': 'active',
        'dropdown1': 'dropdown-conatiner1',
    }
    if request.user.is_superuser:
        return render(request, 'product/add_category.html', context)
    else:
        return render(request, 'main/not_authorised.html')


# def category_delete(request, slug1):
#     instance = get_object_or_404(Category, slug1=slug1)
#     instance.delete()
#     return redirect('product:category')


def product_detail(request, slug):
    instance = get_object_or_404(Product, slug=slug)
    context = {
        'instance': instance,
        'active4': 'active',
        'dropdown1': 'dropdown-conatiner1',
    }
    return render(request, 'product/product_details.html', context)


def product_edit(request, slug):
    instance = get_object_or_404(Product, slug=slug)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            f = form.save(commit=False)
            f.created_by = request.user
            f.save()
            # return redirect('product:index')
            return HttpResponseRedirect(f.get_absolute_url())
    else:
        form = ProductForm(instance=instance)
    context = {
        'form': form,
        'active4': 'active',
        'dropdown1': 'dropdown-conatiner1',
    }
    if request.user.is_superuser:
        return render(request, 'product/add_product.html', context)
    else:
        return render(request, 'main/not_authorised.html')


def product_delete(request, slug):
    instance = get_object_or_404(Product, slug=slug)
    instance.delete()
    return redirect('product:product')


def price_category_detail(request, slug2):
    instance = get_object_or_404(PriceCategory, slug2=slug2)
    product =  Product.objects.all()
    context = {
        'instance': instance,
        'product': product,
        'active4': 'active',
        'dropdown1': 'dropdown-conatiner1',
    }
    return render(request, 'product/price_category_details.html', context)


def price_category_edit(request, slug2):
    instance = get_object_or_404(PriceCategory, slug2=slug2)
    if request.method == 'POST':
        form = PriceCategoryForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            f = form.save(commit=False)
            f.created_by = request.user
            f.save()
            # return redirect('product:index')
            return HttpResponseRedirect(f.get_absolute_url2())
    else:
        form = PriceCategoryForm(instance=instance)
    context = {
        'form': form,
        'active4': 'active',
        'dropdown1': 'dropdown-conatiner1',
    }
    if request.user.is_superuser:
        return render(request, 'product/add_price_category.html', context)
    else:
        return render(request, 'main/not_authorised.html')


def price_category_delete(request, slug2):
    instance = get_object_or_404(PriceCategory, slug2=slug2)
    instance.delete()
    return redirect('product:price_category')

templates/product/add_category.html
{% extends 'base.html' %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
        {% endfor %}
        <button type="submit">Create</button>
    </form>

{% endblock %}

templates/product/add_price_category.html
{% extends 'base.html' %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
        {% endfor %}
        <button type="submit">Create</button>
    </form>

{% endblock %}

templates/product/add_product.html
{% extends 'base.html' %}
{% block content %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }}
            {{ field }}<br/>
            {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
        {% endfor %}
        <button type="submit">Create</button>
    </form>

{% endblock %}

templates/product/category.html
{% extends 'base.html' %}
{% block content %}


<div class="container" style="margin:0px;padding:0px 0px 0px 0px;">
    <div class="col-sm-6" style="color:grey;font-family:">
        <h2>
            <b>CATEGORY</b>
        </h2>
    </div>
    {% if request.user.is_superuser %}
        <div class="col-sm-6" align="right" style="margin-top:15px;">
            <a href="{% url 'product:add_category' %}" class="btn btn-info">
                <i class="glyphicon glyphicon-plus"></i> Create New
            </a>
        </div>
    {% endif %}
</div>
<hr/>

<h3>
    <span style="color:#1dadc6;font-family:serif">Top News</span>
</h3>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead style="background-color:black;color:white">
        <tr>
            <th>
                NAME
            </th>
            <th>
                POSTED BY
            </th>
            <th>
                POSTED ON
            </th>
            <th>
                PRODUCT(s)
             </th>
            <th>
                VIEW
            </th>
            <th>
                EDIT
            </th>
            <th>
                DELETE
            </th>
        </tr>
    </thead>
    {% for cat in category %}
        <tr>
            <td>
                {{cat.category}}
            </td>
            <td>
                {{cat.created_by}}
            </td>
            <td>
                {{cat.timestamp}}
            </td>
            <td>
                -
            </td>
            <td>
                <a href="{{cat.get_absolute_url1}}" class="btn btn-default btn-sm" style="align:right;">
                    view
                </a>
            </td>
            <td>
                <a href="{{cat.get_absolute_url1}}edit" class="btn btn-info btn-sm" style="align:right;">
                    <i class="glyphicon glyphicon-pencil"></i>
                </a>
            </td>
            <td>
                <a href="{{cat.get_absolute_url1}}delete" class="btn btn-danger btn-sm" style="align:right;">
                    <i class="glyphicon glyphicon-trash"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
</table>
<br/>


    <!--<hr/>-->
    <!--<div class="container">-->
        <!--{% for cat in category %}-->
            <!--<a href="{{cat.get_absolute_url1}}" class="btn btn-default">{{ cat.category }}</a><hr/>-->
        <!--{% endfor %}-->
    <!--</div>-->
{% endblock %}

templates/product/category_details.html
{% extends 'base.html' %}
{% block content %}



<div class="container" style="margin:0px;padding:0px 0px 0px 0px;">
    <div class="col-sm-6" style="color:grey;font-family:">
        <h2>
            <b>{{instance.category}}</b>
        </h2>
    </div>
    {% if request.user.is_superuser %}
        <div class="col-sm-6" align="right" style="margin-top:15px;">
            <a href="{% url 'product:add_product' %}" class="btn btn-info">
                <i class="glyphicon glyphicon-plus"></i> Create New
            </a>
        </div>
    {% endif %}
</div>
<hr/>

<h3>
    <span style="color:#1dadc6;font-family:serif">Products in {{instance.category}}</span>
</h3>
<table class="table table-striped table-bordered table-hover" align="center">
    <thead style="background-color:black;color:white">
        <tr>
            <th>
                NAME
            </th>
            <th>
                PRODUCT CODE
            </th>
            <th>
                POSTED BY
            </th>
            <th>
                POSTED ON
            </th>
            <th>
                PRICE
            </th>
            <th>
                DISCOUNT
            </th>
            <th>
                STATUS
            </th>
            <th>
                VIEW
            </th>
            <th>
                EDIT
            </th>
            <th>
                DELETE
            </th>
        </tr>
    </thead>
    {% for pro in product %}
        {% if pro.category.category == instance.category %}
            <tbody>
                <tr>
                    <td>
                        {{pro.name}}
                    </td>
                    <td>
                        {{pro.product_code}}
                    </td>
                    <td>
                        {{pro.created_by}}
                    </td>
                    <td>
                        {{pro.timestamp}}
                    </td>
                    <td>
                        {{pro.price}}
                    </td>
                    <td>
                        {{pro.discount}}
                    </td>
                    <td>
                        {{pro.status}}
                    </td>
                    <td>
                        <a href="{{pro.get_absolute_url}}" class="btn btn-info btn-sm" style="align:right;">
                            view
                        </a>
                    </td>
                    <td>
                        <a href="{{pro.get_absolute_url}}edit" class="btn btn-info btn-sm" style="align:right;">
                            <i class="glyphicon glyphicon-pencil"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{{pro.get_absolute_url}}delete" class="btn btn-danger btn-sm" style="align:right;">
                            <i class="glyphicon glyphicon-trash"></i>
                        </a>
                    </td>
                </tr>
            </tbody>
        {% endif %}
    {% endfor %}
</table>
<br/>


    <!--<div class="container">-->
        <!--<div>-->
            <!--<center>-->
                <!--<h2>-->
                    <!--{{ instance.category }}-->
                <!--</h2>-->
            <!--</center>-->
            <!--<div align="right">-->
                <!--{% if instance.created_by == request.user %}-->
                    <!--<a href="{{instance.get_absolute_url1}}edit" class="btn btn-info">Edit Category Name</a>-->
                <!--{% endif %}-->
            <!--</div>-->
        <!--</div>-->
        <!--<hr/>-->
        <!--{% for pro in product %}-->
            <!--{% if pro.category.category == instance.category %}-->
                <!--<a href="{{pro.get_absolute_url}}" class="btn btn-default">{{pro.name}}</a><hr/>-->
            <!--{% endif %}-->
        <!--{% endfor %}-->
        <!--</div>-->



{% endblock %}

templates/product/price_category.html
{% extends 'base.html' %}
{% block content %}



<div class="container" style="margin:0px;padding:0px 0px 0px 0px;">
    <div class="col-sm-6" style="color:grey;font-family:">
        <h2>
            <b>PRICE CATEGORY</b>
        </h2>
    </div>
    {% if request.user.is_superuser %}
        <div class="col-sm-6" align="right" style="margin-top:15px;">
            <a href="{% url 'product:add_price_category' %}" class="btn btn-info">
                <i class="glyphicon glyphicon-plus"></i> Create New
            </a>
        </div>
    {% endif %}
</div>
<hr/>

<h3>
    <span style="color:#1dadc6;font-family:serif">Top News</span>
</h3>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead style="background-color:black;color:white">
        <tr>
            <th>
                PRICE
            </th>
        </tr>
    </thead>
    {% for pr in price %}
        <tr>
            <td>
                {{pr.price}}
            </td>
        </tr>
    {% endfor %}
</table>
<br/>

{% endblock %}

templates/product/price_category_details.html
{% extends 'base.html' %}
{% block content %}


    <div class="container">
        <div>
            <center>
                <h2>
                    {{ instance.price }}
                </h2>
            </center>
            <div align="right">
                {% if instance.created_by == request.user %}
                    <a href="{{instance.get_absolute_url2}}edit" class="btn btn-info">Edit</a>
                {% endif %}
            </div>
        </div>
        <hr/>

{% endblock %}

templates/product/product.html
{% extends 'base.html' %}
{% block content %}



<div class="container" style="margin:0px;padding:0px 0px 0px 0px;">
    <div class="col-sm-6" style="color:grey;font-family:">
        <h2>
            <b>PRODUCT</b>
        </h2>
    </div>
    {% if request.user.is_superuser %}
        <div class="col-sm-6" align="right" style="margin-top:15px;">
            <a href="{% url 'product:add_product' %}" class="btn btn-info">
                <i class="glyphicon glyphicon-plus"></i> Create New
            </a>
        </div>
    {% endif %}
</div>
<hr/>

<h3>
    <span style="color:#1dadc6;font-family:serif">Top News</span>
</h3>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead style="background-color:black;color:white">
        <tr>
            <th>
                NAME
            </th>
            <th>
                PRODUCT CODE
            </th>
            <th>
                POSTED BY
            </th>
            <th>
                POSTED ON
            </th>
            <th>
                PRICE
            </th>
            <th>
                DISCOUNT
            </th>
            <th>
                STATUS
            </th>
            <th>
                VIEW
            </th>
            <th>
                EDIT
            </th>
            <th>
                DELETE
            </th>
        </tr>
    </thead>
    {% for pro in product %}
        <tr>
            <td>
                {{pro.name}}
            </td>
            <td>
                {{pro.product_code}}
            </td>
            <td>
                {{pro.created_by}}
            </td>
            <td>
                {{pro.timestamp}}
            </td>
            <td>
                {{pro.price}}
            </td>
            <td>
                {{pro.discount}}
            </td>
            <td>
                {{pro.status}}
            </td>
            <td>
                <a href="{{pro.get_absolute_url}}" class="btn btn-default btn-sm" style="align:right;">
                    view
                </a>
            </td>
            <td>
                <a href="{{pro.get_absolute_url}}edit" class="btn btn-info btn-sm" style="align:right;">
                    <i class="glyphicon glyphicon-pencil"></i>
                </a>
            </td>
            <td>
                <a href="{{pro.get_absolute_url}}delete" class="btn btn-danger btn-sm" style="align:right;">
                    <i class="glyphicon glyphicon-trash"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
</table>
<br/>



    <!--<hr/>-->
    <!--<div class="container">-->
        <!--{% for pro in product %}-->
            <!--<a href="{{pro.get_absolute_url}}" class="btn btn-default">{{ pro.name }}</a><hr/>-->
        <!--{% endfor %}-->
    <!--</div>-->

{% endblock %}

templates/product/product_details.html
{% extends 'base.html' %}
{% block content %}


    <div class="container">
        Product: {{ instance.name }}<br/>
        Description: {{ instance.description }}<br/>
        Product Code: {{instance.product_code}}<br/>
        Category: {{ instance.category }}<br/>
        {% if instance.image %}
            <img src="{{ instance.image.url }}" height="100px" width="100px"><br/>
        {% else %}
            <img src="https://www.brother.ca/resources/images/no-product-image.png" height="100px" width="100px"><br/>
        {% endif %}
        Price: {{ instance.price }}<br/>
        Discount: {{ instance.discount }}<br/>
        Tax: {{ instance.tax }}<br/>
        Active: {{ instance.status }}<br/>
        <br/>
        {% if instance.created_by == request.user %}
            <a href="{{instance.get_absolute_url}}edit" class="btn btn-info">Edit</a>
            <a href="#myModal" class="trigger-btn btn btn-danger btn-sm" data-toggle="modal">
                Delete
            </a>

            <div id="myModal" class="modal fade">
                <div class="modal-dialog modal-confirm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <div class="icon-box">
                                <i class="material-icons">&#xE5CD;</i>
                            </div>
                            <h4 class="modal-title">Are you sure?</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            </div>
                        <div class="modal-body">
                            <p>Do you really want to delete these records? This process cannot be undone.</p>
                        </div>
                        <div class="modal-footer">
                            <a type="button" class="btn btn-info" data-dismiss="modal">Cancel</a>
                            <a href="{{instance.get_absolute_url}}delete" class="btn btn-info">
                                Delete
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        <hr/>
    </div>

{% endblock %}