msg/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    # url(r'^$', msg, name='msg'),
    url(r'^msg_list/$', msg, name='msg'),
    url(r'^add_msg/$', msg_add, name="msg_add"),
    # id,slug based url below this'
    url(r'^msg_list/(\d+)/', msg_user_add, name="msg_user_add"),
    # url(r'^add_msg/(\d+)/', msg_user_add, name="msg_user_add"),
    url(r'^(?P<slug>[\w-]+)/$', msg_details, name='msg_details'),
    url(r'^(?P<slug>[\w-]+)/edit/', msg_edit, name='msg_edit'),
    url(r'^(?P<slug>[\w-]+)/delete/', msg_delete, name='msg_delete'),
]

order/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^new_order/', new_order, name='new_order'),
    url(r'^all_order/', all_order, name='all_order'),
    url(r'^(\d+)/$', order_details, name='order_details'),
    url(r'^(\d+)/edit/', order_edit, name='order_edit'),
    url(r'^(\d+)/delete/', order_delete, name='order_delete'),
]

sample_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('main.urls', 'main'), namespace="main")),
    url(r'^product/', include(('product.urls', 'product'), namespace="product")),
    url(r'^order/', include(('order.urls', 'order'), namespace="order")),
]

order/models.py
from django.db import models
from product.models import *
from main.models1 import *


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True, blank=True, null=True)
    remark = models.CharField(max_length=1000, blank=True, null=True)
    quantity = models.PositiveIntegerField(blank=True, null=True)
    price = models.PositiveIntegerField(blank=True, null=True)
    discount = models.PositiveIntegerField(blank=True, null=True)
    tax = models.PositiveIntegerField(blank=True, null=True)
    total = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.product)

order/forms.py
from django import forms
from .models import *

class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = [
            'customer',
            'remark',
            'product',
            'quantity',
            'price',
            'discount',
            'tax',
            'total',
        ]

order/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from.forms import *
from .models import *


def new_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            f = form.save()
            f.save()
            return redirect('order:order_details', f.id )
            # return HttpResponseRedirect('')
    else:
        form = OrderForm()
    context = {
        'form': form,
        'active6': 'active',
        'dropdown3': 'dropdown-container1',
    }
    if request.user.is_superuser:
        return render(request, 'order/new_order.html', context)
    else:
        return render(request, 'main/not_authenticated.html')


def all_order(request):
    order = Order.objects.all()
    context = {
        'order': order,
        'active6': 'active',
        'dropdown3': 'dropdown-container1',
    }
    return render(request, 'order/all_order.html', context)


def order_details(request, order_id):
    instance = Order.objects.get(id=order_id)
    context = {
        'instance': instance,
        'active6': 'active',
        'dropdown3': 'dropdown-container1',
    }
    if request.user.is_superuser:
        return render(request, 'order/order_details.html', context)
    else:
        return render(request, 'main/not_authenticated.html')


def order_edit(request, order_id):
    instance = Order.objects.get(id=order_id)
    if request.method == 'POST':
        form = OrderForm(request.POST, instance=instance)
        if form.is_valid():
            f = form.save()
            f.save()
            return redirect('order:order_details', f.id )
            # return HttpResponseRedirect('')
    else:
        form = OrderForm(instance=instance)
    context = {
        'form': form,
        'active6': 'active',
        'dropdown3': 'dropdown-container1',
    }
    if request.user.is_superuser:
        return render(request, 'order/new_order.html', context)
    else:
        return render(request, 'main/not_authenticated.html')


def order_delete(request, order_id):
    instance = Order.objects.get(id=order_id)
    instance.delete()
    return redirect('order:all_order')

templates/order/all_order.html
{% extends 'base.html' %}
{% block content %}




<div class="container" style="margin:0px;padding:0px 0px 0px 0px;">
    <div class="col-sm-6" style="color:grey;font-family:">
        <h2>
            <b>ORDER</b>
        </h2>
    </div>
    {% if request.user.is_superuser %}
        <div class="col-sm-6" align="right" style="margin-top:15px;">
            <a href="{% url 'order:new_order' %}" class="btn btn-info">
                <i class="glyphicon glyphicon-plus"></i> Create New
            </a>
        </div>
    {% endif %}
</div>
<hr/>

<h3>
    <span style="color:#1dadc6;font-family:serif">Top News</span>
</h3>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead style="background-color:black;color:white">
        <tr>
            <th>
                PRODUCT
            </th>
            <th>
                CUSTOMER
            </th>
            <th>
                ORDERED ON
            </th>
            <th>
                QUANTITY
            </th>
            <th>
                PRICE(per item)
            </th>
            <th>
                DISCOUNT
            </th>
            <th>
                TAX
            </th>
            <th>
                TOTAL
            </th>
            <th>
                VIEW
            </th>
            <th>
                EDIT
            </th>
            <th>
                DELETE
            </th>
        </tr>
    </thead>
    {% for o in order %}
        <tr>
            <td>
                {{o.product}}
            </td>
            <td>
                {{o.customer}}
            </td>
            <td>
                {{o.date}}
            </td>
            <td>
                {{o.quantity}}
            </td>
            <td>
                {{o.price}}
            </td>
            <td>
                {{o.discount}}
            </td>
            <td>
                {{o.tax}}
            </td>
            <td>
                {{o.total}}
            </td>
            <td>
                <a href="{% url 'order:order_details' o.id %}" class="btn btn-default btn-sm" style="align:right;">
                    view
                </a>
            </td>
            <td>
                <a href="{% url 'order:order_edit' o.id %}" class="btn btn-info btn-sm" style="align:right;">
                    <i class="glyphicon glyphicon-pencil"></i>
                </a>
            </td>
            <td>
                <a href="{% url 'order:order_delete' o.id %}" class="btn btn-danger btn-sm" style="align:right;">
                    <i class="glyphicon glyphicon-trash"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
</table>
<br/>




    <!--{% for o in order %}-->
        <!--<a href="{% url 'order:order_details' o.id %}" class="btn btn-default">-->
            <!--{{ o }}-->
        <!--</a>-->
        <!--<hr/>-->
    <!--{% endfor %}-->

{% endblock %}

templates/order/new_order.html
{% extends 'base.html' %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
        {% endfor %}
        <button type="submit">Create</button>
    </form>

{% endblock %}

templates/order/order_details.html
{% extends 'base.html' %}
{% block content %}

Product - {{instance.product}}<br/>
Customer - {{instance.customer}}<br/>
<a href="{% url 'order:order_edit' instance.id %}">Edit</a>.     .
<a href="#myModal" class="trigger-btn btn btn-danger btn-sm" data-toggle="modal">
    Delete
</a>

<div id="myModal" class="modal fade">
	<div class="modal-dialog modal-confirm">
		<div class="modal-content">
			<div class="modal-header">
				<div class="icon-box">
					<i class="material-icons">&#xE5CD;</i>
				</div>
				<h4 class="modal-title">Are you sure?</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			    </div>
			<div class="modal-body">
				<p>Do you really want to delete these records? This process cannot be undone.</p>
			</div>
			<div class="modal-footer">
				<a type="button" class="btn btn-info" data-dismiss="modal">Cancel</a>
                <a href="{% url 'order:order_delete' instance.id %}" class="btn btn-info">Delete</a>
                    Delete
                </a>
			</div>
		</div>
	</div>
</div>

{% endblock %}